# Project information
site_name: Home Assistant Assistant
site_url: "https://www.awesome-ha.com"
site_description: "A curated list of awesome Home Assistant resources for automating every aspect of your home"
site_author: "Lon Naylor"
copyright: "Copyright - Lon Naylor. Creative Commons Attribution 4.0."

# Repository
repo_name: "awesome-home-assistant"
repo_url: "https://github.com/frenck/awesome-home-assistant"

# Theme configuration
theme:
  name: "material"
  logo: "https://www.awesome-ha.com/images/icon.svg"
  language: "en"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: "light-blue"
      accent: "pink"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: "blue"
      accent: "pink"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate
extra_css:
  - css/extra.css

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/lonnaylor"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/lonnaylor"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/frenck"
    - icon: fontawesome/brands/twitch
      link: "https://twitch.tv/frenck"
    - icon: fontawesome/brands/youtube
      link: "https://youtube.com/lonnaylor"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/lonnaylor"

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists

# The pages to serve
nav:
  - Home: index.md
  - Add-ons: addons.md
  - Automations: automations.md
  - Dashboards: dashboards.md
  - Hardware: hardware.md
  - Integrations: integrations.md
  - Resources: resources.md
  - Scripts: scripts.md
  - Images: images.md


plugins:
  - git-revision-date-localized:
      type: timeago
  - search
